name: Build APK and Create GitHub Release

on:
  push:
    branches:
      - master  # Triggers on pushes to the master branch

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK for Android
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'correto'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the APK
      - name: Build the APK
        run: ./gradlew assembleRelease

      # Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: app/build/outputs/apk/release/*.apk  # Adjust path as necessary

      # Create a Release on GitHub
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}  # Automatically increment version
          release_name: APK Release v${{ github.run_number }}
          body: |
            This release contains the latest build of the APK.
          draft: false
          prerelease: false

      # Upload the APK to the Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/*.apk  # Adjust path as necessary
          asset_name: MyApp-v${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
